
// this file was generated by vision-precompute.exe at 2025-02-02 18:42:28
// it took 0:0.001 s
// please do not manually modify 

#pragma once 

#include "math/basic_types.h" 

namespace vision { 
using namespace ocarina;
const float SpecularBxDFSet_Table[50] = {
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 
	24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 
	36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 
	48, 49
};

const float2 MetallicBxDFSet_Table[50] = {
	float2(0, 1), float2(2, 3), float2(4, 5), float2(6, 7), float2(8, 9), float2(10, 11), 
	float2(12, 13), float2(14, 15), float2(16, 17), float2(18, 19), float2(20, 21), float2(22, 23), 
	float2(24, 25), float2(26, 27), float2(28, 29), float2(30, 31), float2(32, 33), float2(34, 35), 
	float2(36, 37), float2(38, 39), float2(40, 41), float2(42, 43), float2(44, 45), float2(46, 47), 
	float2(48, 49), float2(50, 51), float2(52, 53), float2(54, 55), float2(56, 57), float2(58, 59), 
	float2(60, 61), float2(62, 63), float2(64, 65), float2(66, 67), float2(68, 69), float2(70, 71), 
	float2(72, 73), float2(74, 75), float2(76, 77), float2(78, 79), float2(80, 81), float2(82, 83), 
	float2(84, 85), float2(86, 87), float2(88, 89), float2(90, 91), float2(92, 93), float2(94, 95), 
	float2(96, 97), float2(98, 99)
};

const float4 MetallicBxDFSet2_Table[50] = {
	float4(0, 1, 2, 3), float4(4, 5, 6, 7), float4(8, 9, 10, 11), 
	float4(12, 13, 14, 15), float4(16, 17, 18, 19), float4(20, 21, 22, 23), 
	float4(24, 25, 26, 27), float4(28, 29, 30, 31), float4(32, 33, 34, 35), 
	float4(36, 37, 38, 39), float4(40, 41, 42, 43), float4(44, 45, 46, 47), 
	float4(48, 49, 50, 51), float4(52, 53, 54, 55), float4(56, 57, 58, 59), 
	float4(60, 61, 62, 63), float4(64, 65, 66, 67), float4(68, 69, 70, 71), 
	float4(72, 73, 74, 75), float4(76, 77, 78, 79), float4(80, 81, 82, 83), 
	float4(84, 85, 86, 87), float4(88, 89, 90, 91), float4(92, 93, 94, 95), 
	float4(96, 97, 98, 99), float4(100, 101, 102, 103), float4(104, 105, 106, 107), 
	float4(108, 109, 110, 111), float4(112, 113, 114, 115), float4(116, 117, 118, 119), 
	float4(120, 121, 122, 123), float4(124, 125, 126, 127), float4(128, 129, 130, 131), 
	float4(132, 133, 134, 135), float4(136, 137, 138, 139), float4(140, 141, 142, 143), 
	float4(144, 145, 146, 147), float4(148, 149, 150, 151), float4(152, 153, 154, 155), 
	float4(156, 157, 158, 159), float4(160, 161, 162, 163), float4(164, 165, 166, 167), 
	float4(168, 169, 170, 171), float4(172, 173, 174, 175), float4(176, 177, 178, 179), 
	float4(180, 181, 182, 183), float4(184, 185, 186, 187), float4(188, 189, 190, 191), 
	float4(192, 193, 194, 195), float4(196, 197, 198, 199)
};

} //namespace